version: '3'

services:

  # Web app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_TYPE: mysql+pymysql
      DATABASE_ROOT_PASSWORD: password
      DATABASE_USER: user
      DATABASE_USER_PASSWORD: password
      DATABASE_NAME: quotes_db
      DATABASE_PORT: 3306
      DATABASE_HOSTNAME: mysql
    ports:
      - 8000:8000

  # Database
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: quotes_db
    ports:
      - 3306:3306
    volumes:
      - ./docker-bind-mounts/mysql/data:/var/lib/mysql
    
  # prometheus:
  #   image: prom/prometheus:v2.5.0
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./docker-bind-mounts/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./docker-bind-mounts/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml


  # https://hub.docker.com/r/prom/mysqld-exporter/

  # For easier viewing of database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080